### ISSUE TITLE
RFC 7395: Extensible Messaging and Presence Protocol (XMPP) Subprotocol for WebSocket

### ISSUE THREAD

**Issue by zw5** [horazont/aioxmpp#345] opened 2020-08-02 21:21 UTC
Are there any plans on implementing support for this transport layer?
There's already some libraries that use this protocol such as [this one](https://github.com/Terbau/fortnitepy/blob/master/fortnitepy/xmpp.py)

**Comment by horazont** [comment] 2020-08-03 15:17
Duplicate of #18.

**Closed by horazont** 2020-08-03 15:17 UTC
